/**
 * JobCoachAI — Tailor-only analysis and suggestion panels.
 *
 * Add <TailorResumeInsights /> inside your EXISTING Tailor page.
 * Reads the base resume draft saved by ResumePage from sessionStorage.
 * All suggested changes stay in this component's in-memory tailored copy;
 * this component NEVER calls your database or overwrites the base resume draft.
 *
 * ATS score is local keyword matching, NOT an official ATS score.
 * Sample AI suggestions are demonstration data, NOT generated by an AI service.
 */
import { useEffect, useState, type ComponentProps } from 'react'
import { AtsScorePanel } from '../components/AtsScorePanel'
import { SummaryOptions } from '../components/SummaryOptions'
import { ResumeSuggestions } from '../components/ResumeSuggestions'
import { analyzeResumeForJob, generateSummaryOptions } from '../features/resume/resumeInsights'
import { sampleResumeRecommendations } from '../features/resume/resumeSuggestions'
import type { ResumeProfile, ResumeSaveRequest } from '../features/resume/resumeData'
import type { ResumeRecommendation, SuggestionChange } from '../features/resume/resumeSuggestions'
import type { AIResponse, SummaryOption, SummaryTone } from '../types/ai'

// Matches the exact prop type expected by the existing Kiran component.
type Sections = ComponentProps<typeof ResumeSuggestions>['sections']
// The saved ResumePage draft includes a display title; Kiran's component only
// requires the key and entries, so preserve the optional draft-only field.
type TailorSection = Sections[number] & { title?: string }
type Draft = { profile: ResumeProfile; sections: TailorSection[]; filename: string }
const DRAFT_KEY = 'jobcoachai.resumeDraft'

function readDraft(): Draft | null {
  try {
    const raw = sessionStorage.getItem(DRAFT_KEY)
    if (!raw) return null
    const draft: unknown = JSON.parse(raw)
    if (!draft || typeof draft !== 'object') return null
    const d = draft as Partial<Draft>
    if (!d.profile || !Array.isArray(d.sections)) return null
    // Do not share object references with the original draft.
    return JSON.parse(JSON.stringify(d)) as Draft
  } catch {
    return null
  }
}

function asEntries<K extends 'work_experience' | 'education' | 'skills' | 'projects' | 'certifications'>(
  sections: Sections,
  key: K,
): ResumeSaveRequest[K] {
  const entries = sections.find((section) => section.key === key)?.entries ?? []
  // Stored resume sections are the same typed records ResumePage saves.
  return entries.filter((entry) => typeof entry !== 'string' &&
    Object.values(entry).some((value) => typeof value === 'string' && value.trim() !== '')) as ResumeSaveRequest[K]
}

function payloadFromDraft(draft: Draft): ResumeSaveRequest {
  const summaryEntry = draft.sections.find((section) => section.key === 'summary')?.entries[0]
  return {
    resume: {
      full_name: `${draft.profile.first_name} ${draft.profile.last_name}`.trim(),
      email: draft.profile.email,
      phone: draft.profile.phone,
      location: draft.profile.location,
      professional_summary: typeof summaryEntry === 'string'
        ? summaryEntry : draft.profile.professional_summary,
    },
    section_order: draft.sections.map((section, index) => ({
      section_name: section.key as ResumeSaveRequest['section_order'][number]['section_name'],
      section_order: index,
    })),
    work_experience: asEntries(draft.sections, 'work_experience'),
    education: asEntries(draft.sections, 'education'),
    skills: asEntries(draft.sections, 'skills'),
    projects: asEntries(draft.sections, 'projects'),
    certifications: asEntries(draft.sections, 'certifications'),
  }
}

function entryText(entry: Sections[number]['entries'][number]): string {
  if (typeof entry === 'string') return entry
  return Object.entries(entry)
    .filter(([key, value]) => key !== 'id' && key !== 'sort_order' && typeof value === 'string' && value.trim())
    .map(([, value]) => String(value))
    .join(' · ')
}

export interface TailorResumeInsightsProps {
  jobDescription: string
}

export function TailorResumeInsights({ jobDescription }: TailorResumeInsightsProps) {
  const [tailored, setTailored] = useState<Draft | null>(readDraft)
  const [atsResponse, setAtsResponse] = useState<AIResponse | null>(null)
  const [summaryOptions, setSummaryOptions] = useState<SummaryOption[]>([])
  const [appliedTone, setAppliedTone] = useState<SummaryTone | null>(null)
  const [recommendations, setRecommendations] = useState<ResumeRecommendation[]>([])
  const [message, setMessage] = useState('')

  // A changed job description invalidates the previous keyword score and summaries.
  useEffect(() => {
    setAtsResponse(null)
    setSummaryOptions([])
    setAppliedTone(null)
  }, [jobDescription])

  const refreshBaseResume = () => {
    setTailored(readDraft())
    setAtsResponse(null)
    setSummaryOptions([])
    setAppliedTone(null)
    setRecommendations([])
    setMessage('A fresh tailored copy was loaded. Your original resume was not changed.')
  }

  const analyze = () => {
    if (!tailored) {
      setMessage('Build a resume first, then return to this page.')
      return
    }
    if (!jobDescription.trim()) {
      setMessage('Paste a job description before analyzing.')
      return
    }
    const payload = payloadFromDraft(tailored)
    setAtsResponse(analyzeResumeForJob(payload, jobDescription))
    setSummaryOptions(generateSummaryOptions({
      profile: tailored.profile,
      skills: payload.skills.map((skill) => skill.skill_name).filter(Boolean),
      highlights: payload.work_experience.map((entry) => entry.description).filter(Boolean),
    }, jobDescription))
    setAppliedTone(null)
    setMessage('Local keyword analysis completed for your tailored copy.')
  }

  const applySummary = (option: SummaryOption) => {
    setTailored((current) => {
      if (!current) return current
      const existing = current.sections.find((section) => section.key === 'summary')
      const sections: TailorSection[] = existing
        ? current.sections.map((section) => section.key === 'summary'
          ? { ...section, entries: [option.text] } : section)
        : [{ key: 'summary', title: 'Professional summary', entries: [option.text] }, ...current.sections]
      return { ...current, sections }
    })
    setAppliedTone(option.tone)
    setAtsResponse(null) // A prior score is stale after editing the resume.
    setMessage('Summary applied to the tailored copy only. Re-analyze to refresh the score.')
  }

  const applySuggestion = (change: SuggestionChange) => {
    const section = tailored?.sections.find((item) => item.key === change.target.sectionKey)
    const entry = section?.entries[change.target.entryIndex]
    if (entry === undefined || (typeof entry !== 'string' && !(change.target.fieldKey in entry))) {
      setMessage('This suggestion targets a field not present in the tailored resume.')
      return
    }
    setTailored((current) => current && ({
      ...current,
      sections: current.sections.map((item) => item.key !== change.target.sectionKey
        ? item
        : {
          ...item,
          entries: item.entries.map((oldEntry, index) => index !== change.target.entryIndex
            ? oldEntry
            : typeof oldEntry === 'string'
              ? change.newText
              : { ...oldEntry, [change.target.fieldKey]: change.newText }),
        }),
    }))
    setAtsResponse(null)
    setAppliedTone(null)
    setMessage('Suggestion applied to the tailored copy only. Re-analyze to refresh the score.')
  }

  return (
    <section className="resume-suggestions-region" aria-label="Tailor resume analysis">
      <div className="resume-suggestions-toolbar-copy">
        <span className="panel-icon">TAILOR YOUR RESUME</span>
        <h3>Review your resume against a job description</h3>
        <p>Local keyword matching preview — not an official ATS score.</p>
        <p>Your original resume and saved database record are not changed here.</p>
      </div>

      <button type="button" onClick={refreshBaseResume}>
        Reload base resume from Build Your Resume
      </button>

      {!tailored ? (
        <p role="status">No locally saved resume draft found. Build your resume first, then return to Tailor.</p>
      ) : (
        <>
          <p>Uses the job description entered in the form above.</p>
          <button type="button" onClick={analyze} disabled={!jobDescription.trim()}>
            Analyze resume
          </button>
          {atsResponse && <AtsScorePanel response={atsResponse} />}
          {summaryOptions.length > 0 && (
            <SummaryOptions
              options={summaryOptions}
              appliedTone={appliedTone}
              onApply={applySummary}
              onRegenerate={analyze}
            />
          )}

          <section className="resume-suggestions-region" aria-label="AI resume suggestions">
            <div className="resume-suggestions-toolbar-copy">
              <span className="panel-icon">AI SUGGESTIONS</span>
              <p>Edit and apply improvements to your tailored copy.</p>
              <p>Sample suggestions below are demo data, not generated for your resume.</p>
            </div>
            <button type="button" onClick={() => setRecommendations(sampleResumeRecommendations)}>
              Load sample AI suggestions (demo)
            </button>
            <ResumeSuggestions
              recommendations={recommendations}
              sections={tailored.sections}
              onApplySuggestion={applySuggestion}
            />
          </section>

          <section className="resume-preview-section" aria-label="Tailored resume preview">
            <div className="resume-preview-heading">
              <h3>Tailored copy preview</h3>
              <p>Your original resume remains unchanged. Changes here are temporary until a tailored-save or export workflow is connected.</p>
            </div>
            <div className="resume-preview-background">
              <div className="resume-preview-page-frame">
                <h3>{[tailored.profile.first_name, tailored.profile.last_name].filter(Boolean).join(' ') || 'Your name'}</h3>
                <p>{[tailored.profile.email, tailored.profile.phone, tailored.profile.location].filter(Boolean).join(' · ')}</p>
                {tailored.sections.map((section) => {
                  const content = section.entries.map(entryText).filter(Boolean)
                  if (!content.length) return null
                  return (
                    <section key={section.key} className="preview-section">
                      <h4>{section.title ?? section.key.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())}</h4>
                      {content.map((value, index) => <p key={`${section.key}-${index}`}>{value}</p>)}
                    </section>
                  )
                })}
              </div>
            </div>
          </section>
        </>
      )}
      {message && <p role="status">{message}</p>}
    </section>
  )
}

export default TailorResumeInsights
