/**
 * JobCoachAI — Tailor-only analysis and suggestion panels.
 *
 * Add <TailorResumeInsights /> inside your EXISTING Tailor page.
 * Reads the base resume draft saved by ResumePage from sessionStorage.
 * All suggested changes stay in this component's in-memory tailored copy;
 * this component NEVER calls your database or overwrites the base resume draft.
 *
 * ATS score is local keyword matching, NOT an official ATS score.
 * Sample AI suggestions are demonstration data, NOT generated by an AI service.
 */
import { useEffect, useMemo, useState, type ComponentProps } from 'react'
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from 'docx'
import { AtsScorePanel } from '../components/AtsScorePanel'
import { SummaryOptions } from '../components/SummaryOptions'
import { ResumeSuggestions } from '../components/ResumeSuggestions'
import { analyzeResumeForJob, generateSummaryOptions } from '../features/resume/resumeInsights'
import { sampleResumeRecommendations } from '../features/resume/resumeSuggestions'
import type { ResumeProfile, ResumeSaveRequest } from '../features/resume/resumeData'
import type { ResumeRecommendation, SuggestionChange } from '../features/resume/resumeSuggestions'
import type { SummaryOption, SummaryTone } from '../types/ai'

// Matches the exact prop type expected by the existing Kiran component.
type Sections = ComponentProps<typeof ResumeSuggestions>['sections']
// The saved ResumePage draft includes a display title; Kiran's component only
// requires the key and entries, so preserve the optional draft-only field.
type TailorSection = Sections[number] & { title?: string }
type Draft = { profile: ResumeProfile; sections: TailorSection[]; filename: string }
const DRAFT_KEY = 'jobcoachai.resumeDraft'

function readDraft(): Draft | null {
  try {
    const raw = sessionStorage.getItem(DRAFT_KEY)
    if (!raw) return null
    const draft: unknown = JSON.parse(raw)
    if (!draft || typeof draft !== 'object') return null
    const d = draft as Partial<Draft>
    if (!d.profile || !Array.isArray(d.sections)) return null
    // Do not share object references with the original draft.
    return JSON.parse(JSON.stringify(d)) as Draft
  } catch {
    return null
  }
}

function asEntries<K extends 'work_experience' | 'education' | 'skills' | 'projects' | 'certifications'>(
  sections: Sections,
  key: K,
): ResumeSaveRequest[K] {
  const entries = sections.find((section) => section.key === key)?.entries ?? []
  // Stored resume sections are the same typed records ResumePage saves.
  return entries.filter((entry) => typeof entry !== 'string' &&
    Object.values(entry).some((value) => typeof value === 'string' && value.trim() !== '')) as ResumeSaveRequest[K]
}

function payloadFromDraft(draft: Draft): ResumeSaveRequest {
  const summaryEntry = draft.sections.find((section) => section.key === 'summary')?.entries[0]
  return {
    resume: {
      full_name: `${draft.profile.first_name} ${draft.profile.last_name}`.trim(),
      email: draft.profile.email,
      phone: draft.profile.phone,
      location: draft.profile.location,
      professional_summary: typeof summaryEntry === 'string'
        ? summaryEntry : draft.profile.professional_summary,
    },
    section_order: draft.sections.map((section, index) => ({
      section_name: section.key as ResumeSaveRequest['section_order'][number]['section_name'],
      section_order: index,
    })),
    work_experience: asEntries(draft.sections, 'work_experience'),
    education: asEntries(draft.sections, 'education'),
    skills: asEntries(draft.sections, 'skills'),
    projects: asEntries(draft.sections, 'projects'),
    certifications: asEntries(draft.sections, 'certifications'),
  }
}

function entryText(entry: Sections[number]['entries'][number]): string {
  if (typeof entry === 'string') return entry
  return Object.entries(entry)
    .filter(([key, value]) => key !== 'id' && key !== 'sort_order' && typeof value === 'string' && value.trim())
    .map(([, value]) => String(value))
    .join(' · ')
}

export interface TailorResumeInsightsProps {
  jobDescription: string
}

export function TailorResumeInsights({ jobDescription }: TailorResumeInsightsProps) {
  const [tailored, setTailored] = useState<Draft | null>(readDraft)
  const [summaryOptions, setSummaryOptions] = useState<SummaryOption[]>([])
  const [appliedTone, setAppliedTone] = useState<SummaryTone | null>(null)
  const [recommendations, setRecommendations] = useState<ResumeRecommendation[]>([])
  const [message, setMessage] = useState('')
  const [exportMenuOpen, setExportMenuOpen] = useState(false)
  const [exportBusy, setExportBusy] = useState(false)
  const [summaryOpen, setSummaryOpen] = useState(false)
  const [suggestionsOpen, setSuggestionsOpen] = useState(false)
  const [showResetConfirmation, setShowResetConfirmation] = useState(false)

  // Update the compatibility score automatically on Submit and after every tailored edit.
  const atsResponse = useMemo(() => (
    tailored && jobDescription.trim()
      ? analyzeResumeForJob(payloadFromDraft(tailored), jobDescription)
      : null
  ), [tailored, jobDescription])

  // Mounted only after Submit: prepare the professional summary options.
  useEffect(() => {
    const base = readDraft()
    if (!base) {
      setMessage('No local resume draft found. Return to Build Your Resume first.')
      return
    }
    const payload = payloadFromDraft(base)
    setSummaryOptions(generateSummaryOptions({
      profile: base.profile,
      skills: payload.skills.map((skill) => skill.skill_name).filter(Boolean),
      highlights: payload.work_experience.map((entry) => entry.description).filter(Boolean),
    }, jobDescription))
  }, [jobDescription])

  const refreshBaseResume = () => {
    setTailored(readDraft())
    setSummaryOptions([])
    setAppliedTone(null)
    setRecommendations([])
    setMessage('A fresh tailored copy was loaded. Your original resume was not changed.')
    const base = readDraft()
    if (base) {
      const payload = payloadFromDraft(base)
      setSummaryOptions(generateSummaryOptions({
        profile: base.profile,
        skills: payload.skills.map((skill) => skill.skill_name).filter(Boolean),
        highlights: payload.work_experience.map((entry) => entry.description).filter(Boolean),
      }, jobDescription))
    }
  }

  const regenerateSummaries = () => {
    if (!tailored) {
      setMessage('Build a resume first, then return to this page.')
      return
    }
    if (!jobDescription.trim()) {
      setMessage('Paste a job description before analyzing.')
      return
    }
    const payload = payloadFromDraft(tailored)
    setSummaryOptions(generateSummaryOptions({
      profile: tailored.profile,
      skills: payload.skills.map((skill) => skill.skill_name).filter(Boolean),
      highlights: payload.work_experience.map((entry) => entry.description).filter(Boolean),
    }, jobDescription))
    setAppliedTone(null)
    setMessage('Professional summary options refreshed for your tailored copy.')
  }

  const applySummary = (option: SummaryOption) => {
    setTailored((current) => {
      if (!current) return current
      const existing = current.sections.find((section) => section.key === 'summary')
      const sections: TailorSection[] = existing
        ? current.sections.map((section) => section.key === 'summary'
          ? { ...section, entries: [option.text] } : section)
        : [{ key: 'summary', title: 'Professional summary', entries: [option.text] }, ...current.sections]
      return { ...current, sections }
    })
    setAppliedTone(option.tone)
    setMessage('Summary applied to the tailored copy only. Resume match updates automatically.')
  }

  const applySuggestion = (change: SuggestionChange) => {
    const section = tailored?.sections.find((item) => item.key === change.target.sectionKey)
    const entry = section?.entries[change.target.entryIndex]
    if (entry === undefined || (typeof entry !== 'string' && !(change.target.fieldKey in entry))) {
      setMessage('This suggestion targets a field not present in the tailored resume.')
      return
    }
    setTailored((current) => current && ({
      ...current,
      sections: current.sections.map((item) => item.key !== change.target.sectionKey
        ? item
        : {
          ...item,
          entries: item.entries.map((oldEntry, index) => index !== change.target.entryIndex
            ? oldEntry
            : typeof oldEntry === 'string'
              ? change.newText
              : { ...oldEntry, [change.target.fieldKey]: change.newText }),
        }),
    }))
    setAppliedTone(null)
    setMessage('Suggestion applied to the tailored copy only. Resume match updates automatically.')
  }

  // Export the live tailored state, never the original sessionStorage draft.
  const tailoredFilename = () => {
    const base = (tailored?.filename || 'resume').replace(/\.docx?$/i, '')
      .replace(/[<>:"/\\|?*\x00-\x1F]+/g, '-').trim() || 'resume'
    return `${base}-tailored`
  }

  const exportTailoredAsDocx = async () => {
    if (!tailored || exportBusy) return
    setExportBusy(true)
    try {
      const name = [tailored.profile.first_name, tailored.profile.last_name]
        .filter(Boolean).join(' ') || 'Your name'
      const contact = [tailored.profile.email, tailored.profile.phone, tailored.profile.location]
        .filter(Boolean).join(' · ')
      const paragraphs: Paragraph[] = [
        new Paragraph({
          children: [new TextRun({ text: name, bold: true, size: 32 })],
          heading: HeadingLevel.TITLE,
        }),
      ]
      if (contact) paragraphs.push(new Paragraph(contact))
      for (const section of tailored.sections) {
        const content = section.entries.map(entryText).filter(Boolean)
        if (!content.length) continue
        paragraphs.push(new Paragraph({
          text: section.title ?? section.key.replace(/_/g, ' ')
            .replace(/\b\w/g, (letter) => letter.toUpperCase()),
          heading: HeadingLevel.HEADING_1,
        }))
        for (const value of content) paragraphs.push(new Paragraph(value))
      }
      const document = new Document({ sections: [{ children: paragraphs }] })
      const blob = await Packer.toBlob(document)
      const url = URL.createObjectURL(blob)
      const link = window.document.createElement('a')
      link.href = url
      link.download = `${tailoredFilename()}.docx`
      link.click()
      window.setTimeout(() => URL.revokeObjectURL(url), 1000)
      setMessage('Tailored resume DOCX download started. Check your downloads to confirm it saved.')
    } catch (error) {
      console.error('Tailored resume DOCX export failed:', error)
      setMessage('Could not export the tailored resume as DOCX. Please try again.')
    } finally {
      setExportBusy(false)
    }
  }

  const exportTailoredAsPdf = () => {
    if (!tailored) return
    const originalTitle = window.document.title
    window.document.title = tailoredFilename()
    // App.css already targets .resume-preview-page-frame for print, the same
    // class used by the tailored preview below. Only the resume is printed.
    const restoreTitle = () => { window.document.title = originalTitle }
    window.addEventListener('afterprint', restoreTitle, { once: true })
    try {
      window.print()
    } finally {
      window.setTimeout(restoreTitle, 1000)
    }
  }

  return (
    <section className="resume-suggestions-region tailor-results" aria-label="Tailor resume analysis">
      {!tailored ? (
        <p role="status">No locally saved resume draft found. Build your resume first, then return to Tailor.</p>
      ) : (
        <>
          <section aria-label="ATS compatibility analysis" className="tailor-match-section">
            <div className="resume-suggestions-toolbar-copy">
              <span className="panel-icon">RESUME ANALYSIS</span>
              <h3>ATS Compatibility Score</h3>
              <p>Local keyword match preview — not an official ATS assessment.</p>
            </div>
            {atsResponse && <AtsScorePanel response={atsResponse} />}
          </section>

          <section className="tailor-dropdown" aria-label="AI Professional Summary">
            <button type="button" className="tailor-dropdown-trigger" aria-expanded={summaryOpen}
              aria-controls="tailor-summary-content" onClick={() => setSummaryOpen((open) => !open)}>
              <span className="tailor-dropdown-label">
                <span className="panel-icon">AI SUMMARY</span>
                <strong>AI Professional Summary</strong>
                <small>Review summary options and apply a tone to your tailored resume.</small>
              </span>
              <span className={`tailor-dropdown-chevron${summaryOpen ? ' open' : ''}`} aria-hidden="true">⌄</span>
            </button>
            {summaryOpen && (
              <div id="tailor-summary-content" className="tailor-dropdown-body">
                {summaryOptions.length > 0 ? (
                  <SummaryOptions options={summaryOptions} appliedTone={appliedTone}
                    onApply={applySummary} onRegenerate={regenerateSummaries} />
                ) : <p>Submit a job description to generate summary options.</p>}
              </div>
            )}
          </section>

          <section className="tailor-dropdown" aria-label="AI Suggestions">
            <button type="button" className="tailor-dropdown-trigger" aria-expanded={suggestionsOpen}
              aria-controls="tailor-suggestions-content" onClick={() => setSuggestionsOpen((open) => !open)}>
              <span className="tailor-dropdown-label">
                <span className="panel-icon">AI SUGGESTIONS</span>
                <strong>AI Suggestions</strong>
                <small>Review and apply suggested improvements to your tailored copy.</small>
              </span>
              <span className={`tailor-dropdown-chevron${suggestionsOpen ? ' open' : ''}`} aria-hidden="true">⌄</span>
            </button>
            {suggestionsOpen && (
              <div id="tailor-suggestions-content" className="tailor-dropdown-body">
                <p className="tailor-demo-note">Current suggestions are demonstration data, not personalized AI results.</p>
                <button className="button button-secondary" type="button"
                  onClick={() => setRecommendations(sampleResumeRecommendations)}>
                  Load Demo Suggestions
                </button>
                <ResumeSuggestions recommendations={recommendations} sections={tailored.sections}
                  onApplySuggestion={applySuggestion} />
              </div>
            )}
          </section>

          <div className="tailor-insight-actions" style={{ justifyContent: 'flex-end' }}>
            <button className="button button-primary" type="button"
              onClick={() => setShowResetConfirmation(true)}>Reset All Tailored Changes</button>
          </div>

          <section className="resume-preview-section" aria-label="Tailored resume preview">
            <div className="resume-preview-heading">
              <h3>Tailored copy preview</h3>
              <p>Your original resume remains unchanged when you export this tailored copy.</p>
            </div>
            <div className="resume-preview-background">
              <div className="resume-preview-page-frame">
                <h3>{[tailored.profile.first_name, tailored.profile.last_name].filter(Boolean).join(' ') || 'Your name'}</h3>
                <p>{[tailored.profile.email, tailored.profile.phone, tailored.profile.location].filter(Boolean).join(' · ')}</p>
                {tailored.sections.map((section) => {
                  const content = section.entries.map(entryText).filter(Boolean)
                  if (!content.length) return null
                  return (
                    <section key={section.key} className="preview-section">
                      <h4>{section.title ?? section.key.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())}</h4>
                      {content.map((value, index) => <p key={`${section.key}-${index}`}>{value}</p>)}
                    </section>
                  )
                })}
              </div>
            </div>
          </section>
          <div className="resume-bottom-action-buttons">
            <div className="resume-export-actions">
              <button className="button button-primary" type="button"
                aria-haspopup="dialog" aria-expanded={exportMenuOpen}
                onClick={() => setExportMenuOpen(true)}>
                Export Tailored Resume
              </button>
            </div>
          </div>
        </>
      )}
      {message && <p role="status">{message}</p>}
      {exportMenuOpen && tailored && (
        <div className="export-dialog-backdrop" role="presentation">
          <div className="export-dialog" role="dialog" aria-modal="true"
            aria-labelledby="tailored-export-title"
            aria-describedby="tailored-export-description">
            <span className="panel-icon">SAVE AS</span>
            <h3 id="tailored-export-title">Choose a file type</h3>
            <p id="tailored-export-description">
              Download your tailored resume as PDF or DOCX.
            </p>
            <div className="export-dialog-options">
              <button className="button button-primary" type="button"
                disabled={exportBusy}
                onClick={() => {
                  setExportMenuOpen(false)
                  exportTailoredAsPdf()
                }}>
                Save as PDF <span aria-hidden="true">↗</span>
              </button>
              <button className="button button-primary" type="button"
                disabled={exportBusy}
                onClick={() => {
                  setExportMenuOpen(false)
                  void exportTailoredAsDocx()
                }}>
                {exportBusy ? 'Preparing DOCX…' : 'Save as DOCX'} <span aria-hidden="true">↓</span>
              </button>
            </div>
            <button className="export-dialog-cancel" type="button"
              disabled={exportBusy}
              onClick={() => setExportMenuOpen(false)}>Cancel</button>
          </div>
        </div>
      )}
      {showResetConfirmation && (
        <div className="tailor-confirm-backdrop">
          <div className="tailor-confirm-dialog" role="alertdialog" aria-modal="true"
            aria-labelledby="tailor-reset-title" aria-describedby="tailor-reset-description">
            <span className="panel-icon">RESET TAILORED COPY?</span>
            <h3 id="tailor-reset-title">Discard tailored changes?</h3>
            <p id="tailor-reset-description">This reloads your original resume into the tailored preview.
              Your original resume and database record remain unchanged.</p>
            <div className="tailor-confirm-actions">
              <button className="button button-secondary" type="button"
                onClick={() => setShowResetConfirmation(false)}>Keep Current Copy</button>
              <button className="button button-primary" type="button" onClick={() => {
                setShowResetConfirmation(false)
                refreshBaseResume()
              }}>Reset Tailored Copy</button>
            </div>
          </div>
        </div>
      )}
    </section>
  )
}

export default TailorResumeInsights
